### ISSUE TITLE
Branding issues on "Get Started" page and other text changes

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/OfficeAddinDevKit#7]
**Describe the bug**
The capitalization of Office Add-ins should be consistent with branding guidelines.

- "Office Add-ins" (the overall feature or a collection of add-ins)
- "Office Add-in" (a single extension)
- "Excel add-in" (a single, host-specific extension)
- "Excel add-ins" (multiple host-specific extensions)

**Expected behavior**
Here are the instances on the Get Started page that should be corrected. I've also included a couple other suggestions for grammar, style, and clarity.

- "Jump start your Office add-in development experience" -> "Jump start your Office Add-ins development experience."
- "Developing Office Add-in with JavaScript or TypeScript requires NPM and Node.js." -> "Developing Office Add-ins with JavaScript or TypeScript requires NPM and Node.js."
- "Check your environment and get ready for your first Office development." -> "Check your environment to prepare for your first Office Add-in."
- "Build your first Office add-in" -> "Build your first Office Add-in"
- "Preview your Office add-in locally" -> "Preview your Office Add-in locally"

**Screenshots**
![image](https://github.com/user-attachments/assets/788f70f9-da8e-4dde-b020-3f1ae4d6e750)

**Comment by hermanwenhe** [comment]
Thanks Alex. Actually all strings in Dev Kit are in one single file. Are you OK with directly editing the string file and creating a PR in this repo? In this way you can review and refine all strings in Dev Kit. https://dev.azure.com/office/OC/_git/OfficeAddinToolkit?path=/package.nls.json

**Comment by AlexJerabek** [comment]
Thanks @hermanwenhe! I've created an internal PR. Closing this issue.
