### ISSUE TITLE
Add support for Outlook?

### ISSUE THREAD

**Issue by dmendezcreativ** [OfficeDev/OfficeAddinDevKit#8]
There are only options for word, excel, powerpoint.
Do you plan to add support for outlook-extensions in the future?

**Comment by hermanwenhe** [comment]
We're currently working on support for Outlook.

**Comment by dmendezcreativ** [comment]
Thanks for your reply. Is there a rough timeline?

**Comment by hermanwenhe** [comment]
> Thanks for your reply. Is there a rough timeline?

If nothing goes wrong, it should be available within Nov.

**Comment by DevRCRun** [comment]
Anymore info on a timeframe for this? it's nice to see I'm not alone in needing the feature

**Comment by louisik1** [comment]
So....
